services:
    app:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: mysql:8
        container_name: mysql-blis
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0

        volumes:
            - db_data:/var/lib/mysql
    app_test:
        build: .
        ports:
            - "3001:3000"
        volumes:
            - .:/app
            - /app/node_modules
        env_file:
            - .env.test
        depends_on:
            - db
        command: npm test

    db_test:
        image: mysql:8
        container_name: mysql-blis-test
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0

        volumes:
            - db_test_data:/var/lib/mysql

volumes:
    db_data:
    db_test_data:
