services:
    db:
        image: mysql:8
        container_name: mysql-blis-test
        ports:
            - "3308:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
        environment:
            - MYSQL_ROOT_USER=${DATABASE_USER}
            - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
        volumes:
            - db_test_data:/var/lib/mysql

    app_test:
        container_name: app-blis-test
        build: .
        ports:
            - "3001:3000"
        volumes:
            - .:/app
            - /app/node_modules
        env_file:
            - .env
        depends_on:
            - db
        command: ["sh", "-c", "npx prisma migrate dev && npm run test:coverage"]

volumes:
    db_test_data:
